#!/bin/bash

HOURS="$1"

if [ -z "$HOURS" ]; then
  HOURS="1"
fi

/usr/bin/ssh-add -D

# create an anonymous file
trap "rm -f key" EXIT
mkfifo -m 0600 key

# you should have your github secret key in the correct folder
# shellcheck disable=SC2094
lpass show "personal/github-key" --notes > key | /usr/bin/ssh-add -t "$HOURS"H key
