---
name: remst
director_uuid: 11111111111111111111111111

releases:
  - name: remst
    version: latest

instance_groups:
- name: tmux
  instances: 1
  jobs:
  - name: tmux
    release: remst
  vm_type: r3.large
  stemcell: trusty
  persistent_disk_type: 10GB
  azs:
  - eu-west-1a
  networks:
  - name: services

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
